import niswitch

test_data = [
    [
        "BUCK6_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "120",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK12_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "127",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK8_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "118",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK2_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "124",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK1_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "125",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK7_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "119",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK11_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "128",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK0_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "130",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK4_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "122",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK5_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "121",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK10_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "129",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK9_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "117",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK13_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "126",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "BUCK3_TLOAD_CTRL_DUT",
        "AbstractInstrument",
        "123",
        "BUCK_RTRAN_FGEN_CTRL",
        "FGEN_5433_C1_S09, 0",
        "Disconnected",
    ],
    [
        "AIO_5433_VBAT_FGEN_CTRL_DUT",
        "AbstractInstrument",
        "116",
        "VBAT_FGEN_CTRL",
        "FGEN_5433_C1_S09, 1",
        "Disconnected",
    ],
    [
        "LDO9_VPROBE_DUT",
        "AbstractInstrument",
        "189",
        "LDO9_VPROBE_5172",
        "SCOPE_5172_C1_S02, 0",
        "Disconnected",
    ],
    [
        "LDO10_VPROBE_DUT",
        "AbstractInstrument",
        "176",
        "LDO10_VPROBE_5172",
        "SCOPE_5172_C1_S02, 1",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO2_ISENSE_DUT",
        "AbstractInstrument",
        "43",
        "TLOAD1_ISENSE",
        "SCOPE_5172_C1_S02, 2",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO4_ISENSE_DUT",
        "AbstractInstrument",
        "44",
        "TLOAD1_ISENSE",
        "SCOPE_5172_C1_S02, 2",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO9_ISENSE_DUT",
        "AbstractInstrument",
        "38",
        "TLOAD1_ISENSE",
        "SCOPE_5172_C1_S02, 2",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO12_ISENSE_DUT",
        "AbstractInstrument",
        "41",
        "TLOAD1_ISENSE",
        "SCOPE_5172_C1_S02, 2",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO10_ISENSE_DUT",
        "AbstractInstrument",
        "42",
        "TLOAD1_ISENSE",
        "SCOPE_5172_C1_S02, 2",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO13_ISENSE_DUT",
        "AbstractInstrument",
        "40",
        "TLOAD1_ISENSE",
        "SCOPE_5172_C1_S02, 2",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDOINT_ISENSE_DUT",
        "AbstractInstrument",
        "37",
        "TLOAD1_ISENSE",
        "SCOPE_5172_C1_S02, 2",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO15_ISENSE_DUT",
        "AbstractInstrument",
        "39",
        "TLOAD1_ISENSE",
        "SCOPE_5172_C1_S02, 2",
        "Disconnected",
    ],
    [
        "LDO15_VPROBE_DUT",
        "AbstractInstrument",
        "180",
        "LDO15_VPROBE_5172",
        "SCOPE_5172_C1_S02, 3",
        "Disconnected",
    ],
    [
        "LDO12_VPROBE_DUT",
        "AbstractInstrument",
        "178",
        "LDO12_VPROBE_5172",
        "SCOPE_5172_C1_S02, 4",
        "Disconnected",
    ],
    [
        "LDO13_VPROBE_DUT",
        "AbstractInstrument",
        "179",
        "LDO13_VPROBE_5172",
        "SCOPE_5172_C1_S02, 5",
        "Disconnected",
    ],
    [
        "LDOINT_VPROBE_DUT",
        "AbstractInstrument",
        "190",
        "LDOINT_VPROBE_5172",
        "SCOPE_5172_C1_S02, 6",
        "Disconnected",
    ],
    [
        "LDO1_VPROBE_DUT",
        "AbstractInstrument",
        "181",
        "LDO1_VPROBE_5172",
        "SCOPE_5172_C1_S02, 7",
        "Disconnected",
    ],
    [
        "BUCK3_VPROBE_DUT",
        "AbstractInstrument",
        "198",
        "BUCK3_VPROBE_5172",
        "SCOPE_5172_C1_S03, 0",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK10_ISENSE_DUT",
        "AbstractInstrument",
        "51",
        "TLOAD4_ISENSE",
        "SCOPE_5172_C1_S03, 1",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK13_ISENSE_DUT",
        "AbstractInstrument",
        "52",
        "TLOAD4_ISENSE",
        "SCOPE_5172_C1_S03, 1",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK9_ISENSE_DUT",
        "AbstractInstrument",
        "49",
        "TLOAD4_ISENSE",
        "SCOPE_5172_C1_S03, 1",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK3_ISENSE_DUT",
        "AbstractInstrument",
        "50",
        "TLOAD4_ISENSE",
        "SCOPE_5172_C1_S03, 1",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO6_ISENSE_DUT",
        "AbstractInstrument",
        "46",
        "TLOAD4_ISENSE",
        "SCOPE_5172_C1_S03, 1",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO3_ISENSE_DUT",
        "AbstractInstrument",
        "47",
        "TLOAD4_ISENSE",
        "SCOPE_5172_C1_S03, 1",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO8_ISENSE_DUT",
        "AbstractInstrument",
        "45",
        "TLOAD4_ISENSE",
        "SCOPE_5172_C1_S03, 1",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO11_ISENSE_DUT",
        "AbstractInstrument",
        "48",
        "TLOAD4_ISENSE",
        "SCOPE_5172_C1_S03, 1",
        "Disconnected",
    ],
    [
        "LDO6_VPROBE_DUT",
        "AbstractInstrument",
        "186",
        "LDO6_VPROBE_5172",
        "SCOPE_5172_C1_S03, 2",
        "Disconnected",
    ],
    [
        "LDO3_VPROBE_DUT",
        "AbstractInstrument",
        "183",
        "LDO3_VPROBE_5172",
        "SCOPE_5172_C1_S03, 3",
        "Disconnected",
    ],
    [
        "LDO8_VPROBE_DUT",
        "AbstractInstrument",
        "188",
        "LDO8_VPROBE_5172",
        "SCOPE_5172_C1_S03, 4",
        "Disconnected",
    ],
    [
        "LDO11_VPROBE_DUT",
        "AbstractInstrument",
        "177",
        "LDO11_VPROBE_5172",
        "SCOPE_5172_C1_S03, 5",
        "Disconnected",
    ],
    [
        "LDO2_VPROBE_DUT",
        "AbstractInstrument",
        "182",
        "LDO2_VPROBE_5172",
        "SCOPE_5172_C1_S03, 6",
        "Disconnected",
    ],
    [
        "LDO4_VPROBE_DUT",
        "AbstractInstrument",
        "184",
        "LDO4_VPROBE_5172",
        "SCOPE_5172_C1_S03, 7",
        "Disconnected",
    ],
    [
        "BUCK5_VPROBE_DUT",
        "AbstractInstrument",
        "200",
        "BUCK5_VPROBE_5172",
        "SCOPE_5172_C1_S04, 0",
        "Disconnected",
    ],
    [
        "BUCK4_VPROBE_DUT",
        "AbstractInstrument",
        "199",
        "BUCK4_VPROBE_5172",
        "SCOPE_5172_C1_S04, 1",
        "Disconnected",
    ],
    [
        "BUCK10_LX0_ISENSE_DUT",
        "AbstractInstrument",
        "170",
        "BUCK10_LX0_BUCK0_LX1_ISENSE",
        "SCOPE_5172_C1_S04, 2",
        "Disconnected",
    ],
    [
        "BUCK0_LX1_VPROBE_DUT",
        "AbstractInstrument",
        "171",
        "BUCK10_LX0_BUCK0_LX1_ISENSE",
        "SCOPE_5172_C1_S04, 2",
        "Disconnected",
    ],
    [
        "BUCK10_VPROBE_DUT",
        "AbstractInstrument",
        "192",
        "BUCK10_VPROBE_5172",
        "SCOPE_5172_C1_S04, 3",
        "Disconnected",
    ],
    [
        "BUCK13_VPROBE_DUT",
        "AbstractInstrument",
        "195",
        "BUCK13_VPROBE_5172",
        "SCOPE_5172_C1_S04, 4",
        "Disconnected",
    ],
    [
        "BUCK13_LX_ISENSE_DUT",
        "AbstractInstrument",
        "172",
        "BUCK13_LX_ISENSE_BCK0LX2VP",
        "SCOPE_5172_C1_S04, 5",
        "Disconnected",
    ],
    [
        "BUCK0_LX2_VPROBE_DUT",
        "AbstractInstrument",
        "173",
        "BUCK13_LX_ISENSE_BCK0LX2VP",
        "SCOPE_5172_C1_S04, 5",
        "Disconnected",
    ],
    [
        "BUCK9_VPROBE_DUT",
        "AbstractInstrument",
        "204",
        "BUCK9_VPROBE_5172",
        "SCOPE_5172_C1_S04, 6",
        "Disconnected",
    ],
    [
        "BUCK9_LX_ISENSE_DUT",
        "AbstractInstrument",
        "174",
        "BUCK9_LX_BUCK3_LX_ISENSE",
        "SCOPE_5172_C1_S04, 7",
        "Disconnected",
    ],
    [
        "BUCK3_LX_ISENSE_DUT",
        "AbstractInstrument",
        "175",
        "BUCK9_LX_BUCK3_LX_ISENSE",
        "SCOPE_5172_C1_S04, 7",
        "Disconnected",
    ],
    [
        "LDO7_VPROBE_DUT",
        "AbstractInstrument",
        "187",
        "LDO7_VPROBE_5172",
        "SCOPE_5172_C1_S05, 0",
        "Disconnected",
    ],
    [
        "LDO5_VPROBE_DUT",
        "AbstractInstrument",
        "185",
        "LDO5_VPROBE_5172",
        "SCOPE_5172_C1_S05, 1",
        "Disconnected",
    ],
    [
        "BSTLQ_VPROBE_DUT",
        "AbstractInstrument",
        "191",
        "BSTLQ_VPROBE_5172",
        "SCOPE_5172_C1_S05, 2",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO2_ISENSE_DUT",
        "AbstractInstrument",
        "82",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO4_ISENSE_DUT",
        "AbstractInstrument",
        "81",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO9_ISENSE_DUT",
        "AbstractInstrument",
        "78",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO12_ISENSE_DUT",
        "AbstractInstrument",
        "86",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO10_ISENSE_DUT",
        "AbstractInstrument",
        "87",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO13_ISENSE_DUT",
        "AbstractInstrument",
        "85",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDOINT_ISENSE_DUT",
        "AbstractInstrument",
        "77",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO15_ISENSE_DUT",
        "AbstractInstrument",
        "84",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO1_ISENSE_DUT",
        "AbstractInstrument",
        "83",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO7_ISENSE_DUT",
        "AbstractInstrument",
        "79",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO5_ISENSE_DUT",
        "AbstractInstrument",
        "80",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_BSTLQ_ISENSE_DUT",
        "AbstractInstrument",
        "76",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK6_ISENSE_DUT",
        "AbstractInstrument",
        "89",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK12_ISENSE_DUT",
        "AbstractInstrument",
        "91",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK8_ISENSE_DUT",
        "AbstractInstrument",
        "88",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK1_ISENSE_DUT",
        "AbstractInstrument",
        "90",
        "SINK1_ISENSE",
        "SCOPE_5172_C1_S05, 3",
        "Disconnected",
    ],
    [
        "VDD_HI_INT_VPROBE_DUT",
        "AbstractInstrument",
        "32",
        "VDD_IIN1_VPROBE_S",
        "SCOPE_5172_C1_S05, 4",
        "Disconnected",
    ],
    [
        "VDD_LDO3_VPROBE_DUT",
        "AbstractInstrument",
        "27",
        "VDD_IIN1_VPROBE_S",
        "SCOPE_5172_C1_S05, 4",
        "Disconnected",
    ],
    [
        "VDD_LDO14_VPROBE_DUT",
        "AbstractInstrument",
        "29",
        "VDD_IIN1_VPROBE_S",
        "SCOPE_5172_C1_S05, 4",
        "Disconnected",
    ],
    [
        "VDD_BSTLQ_VPROBE_DUT",
        "AbstractInstrument",
        "34",
        "VDD_IIN1_VPROBE_S",
        "SCOPE_5172_C1_S05, 4",
        "Disconnected",
    ],
    [
        "VDD_LDO12_VPROBE_DUT",
        "AbstractInstrument",
        "30",
        "VDD_IIN1_VPROBE_S",
        "SCOPE_5172_C1_S05, 4",
        "Disconnected",
    ],
    [
        "VDD_LDO11_VPROBE_DUT",
        "AbstractInstrument",
        "31",
        "VDD_IIN1_VPROBE_S",
        "SCOPE_5172_C1_S05, 4",
        "Disconnected",
    ],
    [
        "VDD_BUCK8_2_1_IN_VPROBE_DUT",
        "AbstractInstrument",
        "33",
        "VDD_IIN1_VPROBE_S",
        "SCOPE_5172_C1_S05, 4",
        "Disconnected",
    ],
    [
        "VDD_LDO15_VPROBE_DUT",
        "AbstractInstrument",
        "28",
        "VDD_IIN1_VPROBE_S",
        "SCOPE_5172_C1_S05, 4",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO1_ISENSE_DUT",
        "AbstractInstrument",
        "55",
        "TLOAD2_ISENSE",
        "SCOPE_5172_C1_S05, 5",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO7_ISENSE_DUT",
        "AbstractInstrument",
        "53",
        "TLOAD2_ISENSE",
        "SCOPE_5172_C1_S05, 5",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO5_ISENSE_DUT",
        "AbstractInstrument",
        "54",
        "TLOAD2_ISENSE",
        "SCOPE_5172_C1_S05, 5",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BSTLQ_ISENSE_DUT",
        "AbstractInstrument",
        "59",
        "TLOAD2_ISENSE",
        "SCOPE_5172_C1_S05, 5",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK6_ISENSE_DUT",
        "AbstractInstrument",
        "57",
        "TLOAD2_ISENSE",
        "SCOPE_5172_C1_S05, 5",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK12_ISENSE_DUT",
        "AbstractInstrument",
        "58",
        "TLOAD2_ISENSE",
        "SCOPE_5172_C1_S05, 5",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK8_ISENSE_DUT",
        "AbstractInstrument",
        "56",
        "TLOAD2_ISENSE",
        "SCOPE_5172_C1_S05, 5",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK1_ISENSE_DUT",
        "AbstractInstrument",
        "60",
        "TLOAD2_ISENSE",
        "SCOPE_5172_C1_S05, 5",
        "Disconnected",
    ],
    [
        "VDD_BSTLQ_LX_ISENSE_DUT",
        "AbstractInstrument",
        "35",
        "BSTLQ_LX_BUCK6_LX_ISENSE",
        "SCOPE_5172_C1_S05, 6",
        "Disconnected",
    ],
    [
        "BUCK6_LX_ISENSE_DUT",
        "AbstractInstrument",
        "36",
        "BSTLQ_LX_BUCK6_LX_ISENSE",
        "SCOPE_5172_C1_S05, 6",
        "Disconnected",
    ],
    [
        "BUCK6_VPROBE_DUT",
        "AbstractInstrument",
        "201",
        "BUCK6_VPROBE_5172",
        "SCOPE_5172_C1_S05, 7",
        "Disconnected",
    ],
    [
        "BUCK12_VPROBE_DUT",
        "AbstractInstrument",
        "194",
        "BUCK12_VPROBE_5172",
        "SCOPE_5172_C1_S06, 0",
        "Disconnected",
    ],
    [
        "BUCK12_LX_ISENSE_DUT",
        "AbstractInstrument",
        "162",
        "BUCK12_LX_BUCK8_LX_ISENSE",
        "SCOPE_5172_C1_S06, 1",
        "Disconnected",
    ],
    [
        "BUCK8_LX_ISENSE_DUT",
        "AbstractInstrument",
        "163",
        "BUCK12_LX_BUCK8_LX_ISENSE",
        "SCOPE_5172_C1_S06, 1",
        "Disconnected",
    ],
    [
        "BUCK8_VPROBE_DUT",
        "AbstractInstrument",
        "203",
        "BUCK8_VPROBE_5172",
        "SCOPE_5172_C1_S06, 2",
        "Disconnected",
    ],
    [
        "BUCK1_LX1_ISENSE_DUT",
        "AbstractInstrument",
        "164",
        "BUCK1_LX1_BUCK2_LX0_ISENSE",
        "SCOPE_5172_C1_S06, 3",
        "Disconnected",
    ],
    [
        "BUCK2_LX0_ISENSE_DUT",
        "AbstractInstrument",
        "165",
        "BUCK1_LX1_BUCK2_LX0_ISENSE",
        "SCOPE_5172_C1_S06, 3",
        "Disconnected",
    ],
    [
        "BUCK1_VPROBE_DUT",
        "AbstractInstrument",
        "196",
        "BUCK1_VPROBE_5172",
        "SCOPE_5172_C1_S06, 4",
        "Disconnected",
    ],
    [
        "BUCK1_LX2_ISENSE_DUT",
        "AbstractInstrument",
        "166",
        "BUCK1_LX2_BUCK2_LX1_ISENSE",
        "SCOPE_5172_C1_S06, 5",
        "Disconnected",
    ],
    [
        "BUCK2_LX1_ISENSE_DUT",
        "AbstractInstrument",
        "167",
        "BUCK1_LX2_BUCK2_LX1_ISENSE",
        "SCOPE_5172_C1_S06, 5",
        "Disconnected",
    ],
    [
        "BUCK1_LX1_VPROBE_DUT",
        "AbstractInstrument",
        "168",
        "BCK1LX1VP_BUCK2_LX2_ISENSE",
        "SCOPE_5172_C1_S06, 6",
        "Disconnected",
    ],
    [
        "BUCK2_LX2_ISENSE_DUT",
        "AbstractInstrument",
        "169",
        "BCK1LX1VP_BUCK2_LX2_ISENSE",
        "SCOPE_5172_C1_S06, 6",
        "Disconnected",
    ],
    [
        "BUCK6_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "19",
        "RTRAN1_ISENSE",
        "SCOPE_5172_C1_S06, 7",
        "Disconnected",
    ],
    [
        "BUCK12_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "20",
        "RTRAN1_ISENSE",
        "SCOPE_5172_C1_S06, 7",
        "Disconnected",
    ],
    [
        "BUCK8_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "21",
        "RTRAN1_ISENSE",
        "SCOPE_5172_C1_S06, 7",
        "Disconnected",
    ],
    [
        "BUCK2_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "22",
        "RTRAN1_ISENSE",
        "SCOPE_5172_C1_S06, 7",
        "Disconnected",
    ],
    [
        "BUCK1_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "23",
        "RTRAN1_ISENSE",
        "SCOPE_5172_C1_S06, 7",
        "Disconnected",
    ],
    [
        "VDD_MAIN_BUCK_EXT_ISENSE_DUT",
        "AbstractInstrument",
        "18",
        "RTRAN1_ISENSE",
        "SCOPE_5172_C1_S06, 7",
        "Disconnected",
    ],
    [
        "BUCK7_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "24",
        "RTRAN1_ISENSE",
        "SCOPE_5172_C1_S06, 7",
        "Disconnected",
    ],
    [
        "SINK_MUX_SW0_ISENSE_DUT",
        "AbstractInstrument",
        "75",
        "SINK_SW_ISENSE",
        "SCOPE_5172_C1_S07, 0",
        "Disconnected",
    ],
    [
        "SINK_MUX_SW1_ISENSE_DUT",
        "AbstractInstrument",
        "74",
        "SINK_SW_ISENSE",
        "SCOPE_5172_C1_S07, 0",
        "Disconnected",
    ],
    [
        "SINK_MUX_SW2_ISENSE_DUT",
        "AbstractInstrument",
        "73",
        "SINK_SW_ISENSE",
        "SCOPE_5172_C1_S07, 0",
        "Disconnected",
    ],
    [
        "SINK_MUX_SW3_ISENSE_DUT",
        "AbstractInstrument",
        "72",
        "SINK_SW_ISENSE",
        "SCOPE_5172_C1_S07, 0",
        "Disconnected",
    ],
    [
        "SINK_MUX_SW4_ISENSE_DUT",
        "AbstractInstrument",
        "71",
        "SINK_SW_ISENSE",
        "SCOPE_5172_C1_S07, 0",
        "Disconnected",
    ],
    [
        "SINK_MUX_SW5_ISENSE_DUT",
        "AbstractInstrument",
        "70",
        "SINK_SW_ISENSE",
        "SCOPE_5172_C1_S07, 0",
        "Disconnected",
    ],
    [
        "SINK_MUX_SW6_ISENSE_DUT",
        "AbstractInstrument",
        "69",
        "SINK_SW_ISENSE",
        "SCOPE_5172_C1_S07, 0",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK2_ISENSE_DUT",
        "AbstractInstrument",
        "101",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK7_ISENSE_DUT",
        "AbstractInstrument",
        "97",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK11_ISENSE_DUT",
        "AbstractInstrument",
        "104",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK14_ISENSE_DUT",
        "AbstractInstrument",
        "102",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK0_ISENSE_DUT",
        "AbstractInstrument",
        "102",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX1_PD1_DUT",
        "AbstractInstrument",
        "106",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK5_ISENSE_DUT",
        "AbstractInstrument",
        "98",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK4_ISENSE_DUT",
        "AbstractInstrument",
        "99",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK10_ISENSE_DUT",
        "AbstractInstrument",
        "105",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK13_ISENSE_DUT",
        "AbstractInstrument",
        "103",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK9_ISENSE_DUT",
        "AbstractInstrument",
        "96",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_BUCK3_ISENSE_DUT",
        "AbstractInstrument",
        "100",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO6_ISENSE_DUT",
        "AbstractInstrument",
        "93",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO3_ISENSE_DUT",
        "AbstractInstrument",
        "94",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO8_ISENSE_DUT",
        "AbstractInstrument",
        "92",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "SINK_MUX_LDO11_ISENSE_DUT",
        "AbstractInstrument",
        "95",
        "SINK2_ISENSE",
        "SCOPE_5172_C1_S07, 1",
        "Disconnected",
    ],
    [
        "BUCK7_VPROBE_DUT",
        "AbstractInstrument",
        "202",
        "BUCK7_VPROBE_5172",
        "SCOPE_5172_C1_S07, 2",
        "Disconnected",
    ],
    [
        "BUCK11_LX1_ISENSE_DUT",
        "AbstractInstrument",
        "156",
        "BUCK11_LX1_BUCK0_LX4_ISENSE",
        "SCOPE_5172_C1_S07, 3",
        "Disconnected",
    ],
    [
        "BUCK0_LX4_ISENSE_DUT",
        "AbstractInstrument",
        "157",
        "BUCK11_LX1_BUCK0_LX4_ISENSE",
        "SCOPE_5172_C1_S07, 3",
        "Disconnected",
    ],
    [
        "BUCK2_VPROBE_DUT",
        "AbstractInstrument",
        "197",
        "BUCK2_VPROBE_5172",
        "SCOPE_5172_C1_S07, 4",
        "Disconnected",
    ],
    [
        "BUCK7_LX_ISENSE_DUT",
        "AbstractInstrument",
        "158",
        "BUCK7_LX_ISENSE_BCK2LX1VP",
        "SCOPE_5172_C1_S07, 5",
        "Disconnected",
    ],
    [
        "BUCK2_LX1_VPROBE_DUT",
        "AbstractInstrument",
        "159",
        "BUCK7_LX_ISENSE_BCK2LX1VP",
        "SCOPE_5172_C1_S07, 5",
        "Disconnected",
    ],
    [
        "BUCK11_VPROBE_DUT",
        "AbstractInstrument",
        "193",
        "BUCK11_VPROBE_5172",
        "SCOPE_5172_C1_S07, 6",
        "Disconnected",
    ],
    [
        "BUCK11_LX0_ISENSE_DUT",
        "AbstractInstrument",
        "160",
        "BUCK11_LX0_BUCK0_LX3_ISENSE",
        "SCOPE_5172_C1_S07, 7",
        "Disconnected",
    ],
    [
        "BUCK0_LX3_ISENSE_DUT",
        "AbstractInstrument",
        "161",
        "BUCK11_LX0_BUCK0_LX3_ISENSE",
        "SCOPE_5172_C1_S07, 7",
        "Disconnected",
    ],
    [
        "VDD_MAIN_LDO_VPROBE_DUT",
        "AbstractInstrument",
        "11",
        "VDD_IIN1_VPROBE",
        "SCOPE_5172_C1_S08, 0",
        "Disconnected",
    ],
    [
        "VDD_MAIN_SNS_VPROBE_DUT",
        "AbstractInstrument",
        "10",
        "VDD_IIN1_VPROBE",
        "SCOPE_5172_C1_S08, 0",
        "Disconnected",
    ],
    [
        "VDD_BUCK11_7_0_IN_VPROBE_DUT",
        "AbstractInstrument",
        "12",
        "VDD_IIN1_VPROBE",
        "SCOPE_5172_C1_S08, 0",
        "Disconnected",
    ],
    [
        "VDD_BOOST_LDO_VPROBE_DUT",
        "AbstractInstrument",
        "13",
        "VDD_IIN1_VPROBE",
        "SCOPE_5172_C1_S08, 0",
        "Disconnected",
    ],
    [
        "VDD_LDO2_VPROBE_DUT",
        "AbstractInstrument",
        "14",
        "VDD_IIN1_VPROBE",
        "SCOPE_5172_C1_S08, 0",
        "Disconnected",
    ],
    [
        "VDD_LDO4_VPROBE_DUT",
        "AbstractInstrument",
        "15",
        "VDD_IIN1_VPROBE",
        "SCOPE_5172_C1_S08, 0",
        "Disconnected",
    ],
    [
        "VDD_LDO6_VPROBE_DUT",
        "AbstractInstrument",
        "16",
        "VDD_IIN1_VPROBE",
        "SCOPE_5172_C1_S08, 0",
        "Disconnected",
    ],
    [
        "VDD_LDO8_VPROBE_DUT",
        "AbstractInstrument",
        "17",
        "VDD_IIN1_VPROBE",
        "SCOPE_5172_C1_S08, 0",
        "Disconnected",
    ],
    [
        "BUCK0_VPROBE_DUT",
        "AbstractInstrument",
        "140",
        "BUCK0_VPROBE_5172",
        "SCOPE_5172_C1_S08, 1",
        "Disconnected",
    ],
    [
        "BUCK5_LX_ISENSE_DUT",
        "AbstractInstrument",
        "141",
        "BUCK5_LX_BUCK0_LX2_ISENSE",
        "SCOPE_5172_C1_S08, 2",
        "Disconnected",
    ],
    [
        "BUCK0_LX2_ISENSE_DUT",
        "AbstractInstrument",
        "142",
        "BUCK5_LX_BUCK0_LX2_ISENSE",
        "SCOPE_5172_C1_S08, 2",
        "Disconnected",
    ],
    [
        "LDO14_VPROBE_DUT",
        "AbstractInstrument",
        "145",
        "LDO14_VPROBE_5172",
        "SCOPE_5172_C1_S08, 3",
        "Disconnected",
    ],
    [
        "BUCK10_LX1_ISENSE_DUT",
        "AbstractInstrument",
        "143",
        "BUCK10_LX1_BUCK0_LX0_ISENSE",
        "SCOPE_5172_C1_S08, 4",
        "Disconnected",
    ],
    [
        "BUCK0_LX0_ISENSE_DUT",
        "AbstractInstrument",
        "144",
        "BUCK10_LX1_BUCK0_LX0_ISENSE",
        "SCOPE_5172_C1_S08, 4",
        "Disconnected",
    ],
    [
        "BUCK11_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "147",
        "RTRAN2_ISENSE",
        "SCOPE_5172_C1_S08, 5",
        "Disconnected",
    ],
    [
        "BUCK0_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "148",
        "RTRAN2_ISENSE",
        "SCOPE_5172_C1_S08, 5",
        "Disconnected",
    ],
    [
        "BUCK4_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "149",
        "RTRAN2_ISENSE",
        "SCOPE_5172_C1_S08, 5",
        "Disconnected",
    ],
    [
        "BUCK5_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "150",
        "RTRAN2_ISENSE",
        "SCOPE_5172_C1_S08, 5",
        "Disconnected",
    ],
    [
        "BUCK10_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "151",
        "RTRAN2_ISENSE",
        "SCOPE_5172_C1_S08, 5",
        "Disconnected",
    ],
    [
        "BUCK9_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "152",
        "RTRAN2_ISENSE",
        "SCOPE_5172_C1_S08, 5",
        "Disconnected",
    ],
    [
        "BUCK13_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "153",
        "RTRAN2_ISENSE",
        "SCOPE_5172_C1_S08, 5",
        "Disconnected",
    ],
    [
        "BUCK3_RTRAN_ISENSE_DUT",
        "AbstractInstrument",
        "146",
        "RTRAN2_ISENSE",
        "SCOPE_5172_C1_S08, 5",
        "Disconnected",
    ],
    [
        "BUCK4_LX_ISENSE_DUT",
        "AbstractInstrument",
        "154",
        "BUCK4_LX_BUCK0_LX1_ISENSE",
        "SCOPE_5172_C1_S08, 6",
        "Disconnected",
    ],
    [
        "BUCK0_LX1_ISENSE_DUT",
        "AbstractInstrument",
        "155",
        "BUCK4_LX_BUCK0_LX1_ISENSE",
        "SCOPE_5172_C1_S08,6",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK2_ISENSE_DUT",
        "AbstractInstrument",
        "64",
        "TLOAD3_ISENSE",
        "SCOPE_5172_C1_S08, 7",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK7_ISENSE_DUT",
        "AbstractInstrument",
        "61",
        "TLOAD3_ISENSE",
        "SCOPE_5172_C1_S08, 7",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK11_ISENSE_DUT",
        "AbstractInstrument",
        "66",
        "TLOAD3_ISENSE",
        "SCOPE_5172_C1_S08, 7",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_LDO14_ISENSE_DUT",
        "AbstractInstrument",
        "65",
        "TLOAD3_ISENSE",
        "SCOPE_5172_C1_S08, 7",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK0_ISENSE_DUT",
        "AbstractInstrument",
        "67",
        "TLOAD3_ISENSE",
        "SCOPE_5172_C1_S08, 7",
        "Disconnected",
    ],
    [
        "TLOAD_MUX3_PD1_DUT",
        "AbstractInstrument",
        "68",
        "TLOAD3_ISENSE",
        "SCOPE_5172_C1_S08, 7",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK5_ISENSE_DUT",
        "AbstractInstrument",
        "62",
        "TLOAD3_ISENSE",
        "SCOPE_5172_C1_S08, 7",
        "Disconnected",
    ],
    [
        "TLOAD_MUX_BUCK4_ISENSE_DUT",
        "AbstractInstrument",
        "63",
        "TLOAD3_ISENSE",
        "SCOPE_5172_C1_S08, 7",
        "Disconnected",
    ],
    [
        "BUCK4_IOUT_DUT",
        "AbstractInstrument",
        "26",
        "BUCK4_VDD_LDO4_VSENSE",
        "SMU_4139_C3_S03, 0",
        "Connected",
    ],
    [
        "VDD_LDO4_IIN_4139_DUT",
        "AbstractInstrument",
        "25",
        "BUCK4_VDD_LDO4_VSENSE",
        "SMU_4139_C3_S03, 0",
        "Disconnected",
    ],
    [
        "BUCK6_IOUT_DUT",
        "AbstractInstrument",
        "5",
        "BUCK6_VDD_SW345_VSENSE",
        "SMU_4139_C4_S02, 0",
        "Disconnected",
    ],
    [
        "VDD_SW5_IIN_4139_DUT",
        "AbstractInstrument",
        "2",
        "BUCK6_VDD_SW345_VSENSE",
        "SMU_4139_C4_S02, 0",
        "Disconnected",
    ],
    [
        "VDD_SW3_IIN_4139_DUT",
        "AbstractInstrument",
        "4",
        "BUCK6_VDD_SW345_VSENSE",
        "SMU_4139_C4_S02, 0",
        "Disconnected",
    ],
    [
        "VDD_SW4_IIN_4139_DUT",
        "AbstractInstrument",
        "3",
        "BUCK6_VDD_SW345_VSENSE",
        "SMU_4139_C4_S02, 0",
        "Disconnected",
    ],
    [
        "BUCK12_IOUT_DUT",
        "AbstractInstrument",
        "1",
        "BUCK12_VDD_SW6_VSENSE",
        "SMU_4139_C4_S08, 0",
        "Disconnected",
    ],
    [
        "VDD_SW6_IIN_4139_DUT",
        "AbstractInstrument",
        "0",
        "BUCK12_VDD_SW6_VSENSE",
        "SMU_4139_C4_S08, 0",
        "Disconnected",
    ],
    [
        "BUCK3_IOUT_DUT",
        "AbstractInstrument",
        "9",
        "BUCK3_VDD_SW012_VSENSE",
        "SMU_4139_C4_S18, 0",
        "Disconnected",
    ],
    [
        "VDD_SW0_IIN_4139_DUT",
        "AbstractInstrument",
        "8",
        "BUCK3_VDD_SW012_VSENSE",
        "SMU_4139_C4_S18, 0",
        "Disconnected",
    ],
    [
        "VDD_SW1_IIN_4139_DUT",
        "AbstractInstrument",
        "7",
        "BUCK3_VDD_SW012_VSENSE",
        "SMU_4139_C4_S18, 0",
        "Disconnected",
    ],
    [
        "VDD_SW2_IIN_4139_DUT",
        "AbstractInstrument",
        "6",
        "BUCK3_VDD_SW012_VSENSE",
        "SMU_4139_C4_S18, 0",
        "Disconnected",
    ],
    [
        "TCAL_DUT",
        "AbstractInstrument",
        "134",
        "TCAL_TDEV4_FORCE",
        "SMU_4145_C2_S12, 2",
        "Disconnected",
    ],
    [
        "TDEV4_DUT",
        "AbstractInstrument",
        "133",
        "TCAL_TDEV4_FORCE",
        "SMU_4145_C2_S12, 2",
        "Disconnected",
    ],
    [
        "AMUX_AY_DUT",
        "AbstractInstrument",
        "138",
        "AMUX_AY_TDEV2_FORCE",
        "SMU_4145_C2_S13, 1",
        "Disconnected",
    ],
    [
        "TDEV2_DUT",
        "AbstractInstrument",
        "137",
        "AMUX_AY_TDEV2_FORCE",
        "SMU_4145_C2_S13, 1",
        "Disconnected",
    ],
    [
        "AMUX_BY_DUT",
        "AbstractInstrument",
        "136",
        "AMUX_BY_TDEV3_FORCE",
        "SMU_4145_C2_S13, 2",
        "Disconnected",
    ],
    [
        "TDEV3_DUT",
        "AbstractInstrument",
        "135",
        "AMUX_BY_TDEV3_FORCE",
        "SMU_4145_C2_S13, 2",
        "Disconnected",
    ],
    [
        "TDEV1_DUT",
        "AbstractInstrument",
        "132",
        "TDEV1_TDEV5_FORCE",
        "SMU_4145_C2_S15, 2",
        "Disconnected",
    ],
    [
        "TDEV5_DUT",
        "AbstractInstrument",
        "131",
        "TDEV1_TDEV5_FORCE",
        "SMU_4145_C2_S15, 2",
        "Disconnected",
    ],
    [
        "DMM_AMUX_AY_DUT",
        "AbstractInstrument",
        "114",
        "DMM_ATB",
        "DMM_4081_C3_S17, 0",
        "Disconnected",
    ],
    [
        "DMM_AMUX_BY_DUT",
        "AbstractInstrument",
        "113",
        "DMM_ATB",
        "DMM_4081_C3_S17, 0",
        "Disconnected",
    ],
    ["DMM_TCAL_DUT", "AbstractInstrument", "112", "DMM_ATB", "DMM_4081_C3_S17, 0", "Disconnected"],
    ["DMM_TDEV1_DUT", "AbstractInstrument", "111", "DMM_ATB", "DMM_4081_C3_S17, 0", "Disconnected"],
    ["DMM_TDEV2_DUT", "AbstractInstrument", "110", "DMM_ATB", "DMM_4081_C3_S17, 0", "Disconnected"],
    ["DMM_TDEV3_DUT", "AbstractInstrument", "109", "DMM_ATB", "DMM_4081_C3_S17, 0", "Disconnected"],
    ["DMM_TDEV4_DUT", "AbstractInstrument", "108", "DMM_ATB", "DMM_4081_C3_S17, 0", "Disconnected"],
    ["DMM_TDEV5_DUT", "AbstractInstrument", "107", "DMM_ATB", "DMM_4081_C3_S17, 0", "Disconnected"],
    [
        "DMM_ADC_IN_DUT",
        "AbstractInstrument",
        "115",
        "DMM_ATB",
        "DMM_4081_C3_S17, 0",
        "Disconnected",
    ],
]
