# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I2CDebugUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiI2CDebugWindow(object):

    def __init__(self):

        self.central_widget = None
        self.tab_widget = None

        self.tab_damp = None
        self.tab_dpm = None
        self.tab_lint = None
        self.tab_sink = None
        self.tab_tload = None

        self.label_number_of_bytes = None
        self.label_data = None
        self.label_i2c_master = None
        self.label_slave_address = None
        self.label_exec_time = None
        self.label_status = None
        self.label_register = None
        self.label_i2c_read_data = None

        self.combo_box_i2c_master = None
        self.combo_box_damp = None
        self.combo_box_dmp = None
        self.combo_box_lint = None
        self.combo_box_sink = None
        self.combo_box_tload = None

        self.line_edit_damp = None
        self.line_edit_dmp = None
        self.line_edit_lint = None
        self.line_edit_sink = None
        self.line_edit_tload = None
        self.line_edit_slave_address = None
        self.line_edit_exec_time = None
        self.line_edit_status = None
        self.line_edit_number_of_bytes = None
        self.line_edit_data = None

        self.push_button_read = None
        self.push_button_write = None

        self.list_view_read_data = None

    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(600, 302)
        main_window.setMinimumSize(600, 302)
        main_window.setMaximumSize(600, 302)
        main_window.setWindowTitle("I2C Debug UI")

        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.central_widget.setWindowTitle("I2C Debug UI")

        self.tab_widget = QtWidgets.QTabWidget(self.central_widget)
        self.tab_widget.setGeometry(QtCore.QRect(300, 30, 281, 101))
        self.tab_widget.setObjectName("tab_widget")

        self.tab_damp = QtWidgets.QWidget()
        self.tab_damp.setObjectName("tab_damp")

        self.tab_dpm = QtWidgets.QWidget()
        self.tab_dpm.setObjectName("tab_dpm")

        self.tab_lint = QtWidgets.QWidget()
        self.tab_lint.setObjectName("tab_lint")

        self.tab_sink = QtWidgets.QWidget()
        self.tab_sink.setObjectName("tab_sink")

        self.tab_tload = QtWidgets.QWidget()
        self.tab_tload.setObjectName("tab_tload")

        self.label_number_of_bytes = QtWidgets.QLabel(self.central_widget)
        self.label_number_of_bytes.setGeometry(QtCore.QRect(120, 130, 180, 31))
        self.label_number_of_bytes.setAlignment(QtCore.Qt.AlignCenter)
        self.label_number_of_bytes.setObjectName("label_number_of_bytes")
        self.label_number_of_bytes.setText("Number of Bytes")

        self.label_data = QtWidgets.QLabel(self.central_widget)
        self.label_data.setGeometry(QtCore.QRect(160, 190, 101, 31))
        self.label_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_data.setObjectName("label_data")
        self.label_data.setText("Data")

        self.label_i2c_master = QtWidgets.QLabel(self.central_widget)
        self.label_i2c_master.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.label_i2c_master.setAlignment(QtCore.Qt.AlignCenter)
        self.label_i2c_master.setObjectName("label_i2c_master")
        self.label_i2c_master.setText("I2C Master")

        self.label_slave_address = QtWidgets.QLabel(self.central_widget)
        self.label_slave_address.setGeometry(QtCore.QRect(140, 10, 150, 31))
        self.label_slave_address.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slave_address.setObjectName("label_slave_address")
        self.label_slave_address.setText("Slave Address")

        self.label_exec_time = QtWidgets.QLabel(self.central_widget)
        self.label_exec_time.setGeometry(QtCore.QRect(160, 70, 101, 31))
        self.label_exec_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_exec_time.setObjectName("label_exec_time")
        self.label_exec_time.setText("Exec Time")

        self.label_status = QtWidgets.QLabel(self.central_widget)
        self.label_status.setGeometry(QtCore.QRect(10, 70, 101, 31))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.label_status.setText("Status")

        self.label_register = QtWidgets.QLabel(self.central_widget)
        self.label_register.setGeometry(QtCore.QRect(300, 0, 101, 31))
        self.label_register.setAlignment(QtCore.Qt.AlignCenter)
        self.label_register.setObjectName("label_register")
        self.label_register.setText("Register")

        self.label_i2c_read_data = QtWidgets.QLabel(self.central_widget)
        self.label_i2c_read_data.setGeometry(QtCore.QRect(350, 130, 160, 31))
        self.label_i2c_read_data.setAlignment(QtCore.Qt.AlignCenter)
        self.label_i2c_read_data.setObjectName("label_i2c_read_data")
        self.label_i2c_read_data.setText("I2C Read Data")

        self.combo_box_i2c_master = QtWidgets.QComboBox(self.central_widget)
        self.combo_box_i2c_master.setGeometry(QtCore.QRect(10, 40, 101, 31))
        self.combo_box_i2c_master.setObjectName("combo_box_i2c_master")

        self.combo_box_damp = QtWidgets.QComboBox(self.tab_damp)
        self.combo_box_damp.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.combo_box_damp.setObjectName("combo_box_damp")

        self.combo_box_dmp = QtWidgets.QComboBox(self.tab_dpm)
        self.combo_box_dmp.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.combo_box_dmp.setObjectName("combo_box_dmp")

        self.combo_box_lint = QtWidgets.QComboBox(self.tab_lint)
        self.combo_box_lint.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.combo_box_lint.setObjectName("combo_box_lint")

        self.combo_box_sink = QtWidgets.QComboBox(self.tab_sink)
        self.combo_box_sink.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.combo_box_sink.setObjectName("combo_box_sink")

        self.combo_box_tload = QtWidgets.QComboBox(self.tab_tload)
        self.combo_box_tload.setGeometry(QtCore.QRect(20, 20, 151, 31))
        self.combo_box_tload.setObjectName("combo_box_tload")

        self.line_edit_damp = QtWidgets.QLineEdit(self.tab_damp)
        self.line_edit_damp.setGeometry(QtCore.QRect(180, 20, 31, 31))
        self.line_edit_damp.setObjectName("line_edit_damp")

        self.line_edit_dmp = QtWidgets.QLineEdit(self.tab_dpm)
        self.line_edit_dmp.setGeometry(QtCore.QRect(180, 20, 31, 31))
        self.line_edit_dmp.setObjectName("line_edit_dmp")

        self.line_edit_lint = QtWidgets.QLineEdit(self.tab_lint)
        self.line_edit_lint.setGeometry(QtCore.QRect(180, 20, 31, 31))
        self.line_edit_lint.setObjectName("line_edit_lint")

        self.line_edit_sink = QtWidgets.QLineEdit(self.tab_sink)
        self.line_edit_sink.setGeometry(QtCore.QRect(180, 20, 31, 31))
        self.line_edit_sink.setObjectName("line_edit_sink")

        self.line_edit_tload = QtWidgets.QLineEdit(self.tab_tload)
        self.line_edit_tload.setGeometry(QtCore.QRect(180, 20, 31, 31))
        self.line_edit_tload.setObjectName("line_edit_tload")

        self.line_edit_slave_address = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_slave_address.setGeometry(QtCore.QRect(160, 40, 101, 31))
        self.line_edit_slave_address.setObjectName("line_edit_slave_address")

        self.line_edit_exec_time = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_exec_time.setGeometry(QtCore.QRect(160, 100, 101, 31))
        self.line_edit_exec_time.setObjectName("line_edit_exec_time")

        self.line_edit_status = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_status.setGeometry(QtCore.QRect(10, 100, 101, 31))
        self.line_edit_status.setObjectName("line_edit_status")

        self.line_edit_number_of_bytes = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_number_of_bytes.setGeometry(QtCore.QRect(160, 160, 101, 31))
        self.line_edit_number_of_bytes.setObjectName("line_edit_number_of_bytes")

        self.line_edit_data = QtWidgets.QLineEdit(self.central_widget)
        self.line_edit_data.setGeometry(QtCore.QRect(160, 220, 101, 31))
        self.line_edit_data.setObjectName("line_edit_data")

        self.push_button_read = QtWidgets.QPushButton(self.central_widget)
        self.push_button_read.setGeometry(QtCore.QRect(30, 160, 81, 31))
        self.push_button_read.setObjectName("push_button_read")
        self.push_button_read.setText("READ")

        self.push_button_write = QtWidgets.QPushButton(self.central_widget)
        self.push_button_write.setGeometry(QtCore.QRect(30, 220, 81, 31))
        self.push_button_write.setObjectName("push_button_write")
        self.push_button_write.setText("WRITE")

        self.list_view_read_data = QtWidgets.QListView(self.central_widget)
        self.list_view_read_data.setGeometry(QtCore.QRect(380, 160, 101, 91))
        self.list_view_read_data.setObjectName("list_view_read_data")

        self.tab_widget.addTab(self.tab_damp, "DAMP")
        self.tab_widget.addTab(self.tab_dpm, "DPM")
        self.tab_widget.addTab(self.tab_lint, "LINT")
        self.tab_widget.addTab(self.tab_sink, "SINK")
        self.tab_widget.addTab(self.tab_tload, "TLOAD")

        main_window.setCentralWidget(self.central_widget)

        self.tab_widget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(main_window)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiI2CDebugWindow()
    ui.setup_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
